{{- if .Values.redis.enabled }}
{{- $component := "redis" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sayknowmind.svcHost" (dict "root" . "component" $component) }}
  labels: {{- include "sayknowmind.componentLabels" (merge (dict "component" $component) .) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: 6379
      name: redis
  selector: {{- include "sayknowmind.componentSelector" (dict "root" . "component" $component) | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sayknowmind.svcHost" (dict "root" . "component" $component) }}
  labels: {{- include "sayknowmind.componentLabels" (merge (dict "component" $component) .) | nindent 4 }}
spec:
  replicas: 1
  strategy: { type: Recreate }
  selector:
    matchLabels: {{- include "sayknowmind.componentSelector" (dict "root" . "component" $component) | nindent 6 }}
  template:
    metadata:
      labels: {{- include "sayknowmind.componentLabels" (merge (dict "component" $component) .) | nindent 8 }}
    spec:
      serviceAccountName: {{ include "sayknowmind.serviceAccountName" . }}
      {{- include "sayknowmind.podDefaults" . | nindent 6 }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: 6379
          livenessProbe:
            tcpSocket: { port: 6379 }
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 2
            periodSeconds: 5
          resources: {{- toYaml .Values.redis.resources | nindent 12 }}
          securityContext: {{- toYaml .Values.containerSecurityContext | nindent 12 }}
{{- end }}
